version: '3.8'

services:
  # postgres with pgvector extension
  postgres:
    image: pgvector/pgvector:pg16
    container_name: aichat-postgres
    environment:
      POSTGRES_DB: aichatdb
      POSTGRES_USER: aichat
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aichat -d aichatdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: aichat-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data:
